### ISSUE TITLE
Inserting to a nested fieldlist reset last value

### ISSUE THREAD

**Issue by jansedlon** [edmundhung/conform#493]
### Describe the bug and the expected behavior

Give this complex fieldset  (it's a form -> fieldlist -> fieldset -> fieldlist)
<img width="1393" alt="image" src="https://github.com/edmundhung/conform/assets/13948180/ecd6dcc0-d580-4162-a335-b741f46535d7">

When I click on "add option" which inserts to a fieldlist
```
meta.insert({
                    name: fields.customFields.name,
                    defaultValue: {
                      type: "checkbox",
                      choices: [""],
                      required: "off",
                    },
                  })
```

it reset's the last input's value
<img width="1369" alt="image" src="https://github.com/edmundhung/conform/assets/13948180/5d75026d-872e-465b-bb38-296b158a48c5">

Not sure if it's related but i tried to log the result of `getInputProps` and the new fieldlist item always has a `key` which ends with a number. When another item is added, the key is changed to a unique id. I think the value might disappear because the key is recalculated.

<img width="1218" alt="image" src="https://github.com/edmundhung/conform/assets/13948180/9de9822a-a7b6-40ca-b424-a8a2479accdd">

### Conform version

v1.0.2

### Steps to Reproduce the Bug or Issue

Create a form with a fieldlist -> fieldset -> fieldlist

### What browsers are you seeing the problem on?

Chrome

**Comment by edmundhung** [comment]
It might be because you pass the wrong property to the key prop. Please double check if you are passing the key provided by Conform.

**Comment by edmundhung** [comment]
The log with key end with `/2` does looks suspicious. I wonder if this might be related to the default value for the `choices` array. Try remove that and see if it works?

```tsx
meta.insert({
  name: fields.customFields.name,
  defaultValue: {
    type: "checkbox",
    // choices: [""], // Remove this line
    required: "off",
  },
})
```

**Comment by jansedlon** [comment]
@edmundhung hah, you're right, without the `choices`, it's fine :) However I need it with the choices, it's a better UX because users must enter at least 1 option

**Comment by edmundhung** [comment]
Hi @jansedlon, can you prepare a repo with the issue you had? I have an idea where the issue is but I couldn't verify if it resolves your exact issue.

**Comment by jansedlon** [comment]
@edmundhung  heeey, this might work 🙏 Click on "add custom input", fill out the input beneath "options" and add new option. It blanks the filled input

[codesandbox](https://codesandbox.io/p/devbox/lucid-ellis-fx4cdg?file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltugicd000053b6dc4fimnu2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltugicd000023b6dw2hkzsyr%2522%253A%257B%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltugicd000043b6d1fbv52uw%2522%253A%257B%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%252C%2522activeTabId%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltugicd000033b6dzi9a6zsb%2522%253A%257B%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cltugw77100yq3b6dob96sjxq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltugw7by000ddmh60bakgnm7%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by edmundhung** [comment]
Thanks for the sandbox! However, the link doesn't work for me. It says `Devbox not found`.

**Comment by jansedlon** [comment]
@edmundhung  You could have said "thanks for nothing" 😁 Sorry, probably misconfigured permissions. Here you go, tested in anonymous window, should work [sandbox](https://codesandbox.io/p/devbox/lucid-ellis-fx4cdg?file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltugicd000053b6dc4fimnu2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltugicd000023b6dw2hkzsyr%2522%253A%257B%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltxxrott00023b6dcmp1m6dq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltxxrott00023b6dcmp1m6dq%2522%257D%252C%2522cltugicd000043b6d1fbv52uw%2522%253A%257B%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%252C%2522activeTabId%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltugicd000033b6dzi9a6zsb%2522%253A%257B%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cltugw77100yq3b6dob96sjxq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltugw7by000ddmh60bakgnm7%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by mvirbicianskas** [comment]
Hi, I've encountered similar problem and it may be related. The last value of the fieldlist is reset whenever one adds multiple fields and then removes any non-first/last values 🤔 Same repro [sandbox](https://codesandbox.io/p/devbox/still-rgb-smw6lq?workspaceId=33c90faf-9ce0-48bb-976f-80db2d34d802&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltugicd000053b6dc4fimnu2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltugicd000023b6dw2hkzsyr%2522%253A%257B%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltzkjpdd003b2e67wti1pc11%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A73%252C%2522startColumn%2522%253A73%252C%2522endLineNumber%2522%253A73%252C%2522endColumn%2522%253A73%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltzkjpdd003b2e67wti1pc11%2522%257D%252C%2522cltugicd000043b6d1fbv52uw%2522%253A%257B%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%252C%2522activeTabId%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltugicd000033b6dzi9a6zsb%2522%253A%257B%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cltugw77100yq3b6dob96sjxq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltugw7by000ddmh60bakgnm7%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with added `remove`

**Comment by edmundhung** [comment]
This should be fixed on [v1.0.5](https://github.com/edmundhung/conform/releases/tag/v1.0.5).

@mvirbicianskas I think this should also fix your issue, let me know if it isn't.

**Comment by mvirbicianskas** [comment]
Hey, @edmundhung, thank you so much for such a quick response! I've tried to reproduce the issue on the same sandbox with updated dependencies, it seems, unfortunately, that the issue still persists 😭 

https://github.com/edmundhung/conform/assets/17020658/020546fa-6ddc-4f8f-8529-302c83bbfca4

**Comment by edmundhung** [comment]
@mvirbicianskas I have released another fix on [v1.0.6](https://github.com/edmundhung/conform/releases/tag/v1.0.6).

**Comment by mvirbicianskas** [comment]
Hi, @edmundhung, thanks for the speedy response! Looks like the issue still persists when you add few new fields and then try to delete one in the middle, which makes those following fields loose their values. I feel like the keys are just re-generated at this point? Or rather maybe the implementation is incorrect, can you please take a look at the [sandbox](https://codesandbox.io/p/devbox/still-rgb-smw6lq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltugicd000053b6dc4fimnu2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltugicd000023b6dw2hkzsyr%2522%253A%257B%2522id%2522%253A%2522cltugicd000023b6dw2hkzsyr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltzkjpdd003b2e67wti1pc11%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A73%252C%2522startColumn%2522%253A73%252C%2522endLineNumber%2522%253A73%252C%2522endColumn%2522%253A73%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltzkjpdd003b2e67wti1pc11%2522%257D%252C%2522cltugicd000043b6d1fbv52uw%2522%253A%257B%2522id%2522%253A%2522cltugicd000043b6d1fbv52uw%2522%252C%2522activeTabId%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cltugr91g00g93b6dvhfm2mh9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltugicd000033b6dzi9a6zsb%2522%253A%257B%2522id%2522%253A%2522cltugicd000033b6dzi9a6zsb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cltugw77100yq3b6dob96sjxq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu6kbvve0017dric0kk3hbj8%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltugr69h00en3b6dgr3zgi0j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and see if we're using the library correctly? 🤔

**Comment by jansedlon** [comment]
@mvirbicianskas  I'm wondering what that could be. I updated to 1.0.6 and it works 

https://github.com/edmundhung/conform/assets/13948180/2b22bdf3-22b1-4dd3-8fdf-cb4ead839f4e

**Comment by edmundhung** [comment]
Ah yes! I noticed your sandbox used id instead of the key provided by conform. It should work if you are reading the key property from the field metadata when setting the key. The id property is fixed and should be set on the input element only (which getInputProps() does that for you)

**Comment by mvirbicianskas** [comment]
You're right, @edmundhung, thanks for pointing that out! Thank you very much! 🙇
